CREATE TABLE IF NOT EXISTS users
(
  id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL,
  name TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL
);

INSERT INTO users ('id', 'name', 'password', 'admin') VALUES (1, 'admin', 'admin', 1);

CREATE TABLE IF NOT EXISTS news (
   id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL,
   topic TEXT NOT NULL,
   text TEXT NOT NULL,
   date DATETIME NOT NULL,
   author TEXT NOT NULL
)